spring:
  profiles:
    active: local
server:
  port: 8080
  servlet:
    context-path: /

#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #按驼峰命名规则自动匹配到实体类上,不需要用别名
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yaa.model

#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.yaa.model
#  configuration:
#    map-underscore-to-camel-case: true
#  global-config:
#    db-config:
#      table-prefix: bl_
#      id-type: auto

---
spring:
   profiles: local
   mvc:
     favicon:
        enabled: true   #网站默认图标
   datasource:          #数据源
     type: com.alibaba.druid.pool.DruidDataSource
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://rm-8vb13nmd5388n09m6wo.mysql.zhangbei.rds.aliyuncs.com:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
     username: zhaofu
     password: 2MiaoMiao
     dbcp2:
        test-on-borrow: true
        test-while-idle: true
        time-between-eviction-runs-millis: 3600000
        min-evictable-idle-time-millis: 300000
        remove-abandoned-on-borrow: true
        remove-abandoned-timeout: 1800
        max-wait-millis: 60000
        initial-size: 5
        min-idle: 5
        max-idle: 20
        max-total: 20
logging:
  file: /opt/blog/log/site.log
blog:   #自定义属性
  #图片文件存储路径
  filePath: /opt/blog/files/
  #数据库名称
  database: blog
  #MYSQL 登录的命令行 /usr/bin/mysqldump -u 用户名 -p 密码（前面路径代表绝对路径）
  mysqlExec: /usr/bin/mysqldump -uroot -pMysql2018!@#$ blog
  #数据库备份文件路径
  backupPath: /opt/blog/backup/
---
spring:
   profiles: prod
   active: 39.101.184.47
   mvc:
       favicon:
         enabled: false
   datasource:
       type: com.alibaba.druid.pool.DruidDataSource
       driverClassName: com.mysql.jdbc.Driver
       url: jdbc:mysql://rm-8vb13nmd5388n09m6wo.mysql.zhangbei.rds.aliyuncs.com:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
       username: zhaofu
       password: 2MiaoMiao
       initialSize: 1
       minIdle: 3
       maxActive: 20
       # 配置获取连接等待超时的时间
       maxWait: 60000
       # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
       timeBetweenEvictionRunsMillis: 60000
       # 配置一个连接在池中最小生存的时间，单位是毫秒
       minEvictableIdleTimeMillis: 30000
       validationQuery: select 'x'
       testWhileIdle: true
       testOnBorrow: false
       testOnReturn: false


#  ssl:
#    key-store: classpath:ssl/1534728933823.pfx
#    key-store-password: 1534728933823
#    key-store-type: PKCS12
logging:
  file: /opt/blog/log/site.log
blog:   #自定义属性
  #图片文件存储路径
  filePath: /opt/blog/files/
  #数据库名称
  database: blog
  #MYSQL 登录的命令行 /usr/bin/mysqldump -u 用户名 -p 密码（前面路径代表绝对路径）
  mysqlExec: /usr/bin/mysqldump -uroot -pMysql2018!@#$ blog
  #数据库备份文件路径
  backupPath: /opt/blog/backup/